import type { Metadata } from 'next';
import { DocumentShell } from '@/components/document-shell';
export const metadata: Metadata = { title: 'Privacy policy' };
const sections=[{id:'overview',label:'Overview'},{id:'collect',label:'Information handled'},{id:'use',label:'How it is used'},{id:'ai',label:'Online AI'},{id:'sharing',label:'Service providers'},{id:'control',label:'Your controls'},{id:'security',label:'Security'},{id:'contact',label:'Contact'}];
export default function Privacy(){return <DocumentShell kicker="Effective 29 August 2026" title="Privacy policy" intro="This policy explains how Mera Markaz handles information when you use the Android app and this website." sections={sections}>
<section id="overview"><h2>Overview</h2><p>Mera Markaz is a personal finance and utility application published by Logivyre Labs. It is designed to keep guest activity local and provide authenticated users with optional account, encrypted synchronisation and online AI services.</p></section>
<section id="collect"><h2>Information we handle</h2><ul><li><strong>Account information:</strong> name, email address, profile details and provider identifier when you use email, Google or Facebook sign-in.</li><li><strong>Financial records you enter:</strong> expenses, income, categories, budgets, savings, recurring items, reminders and related preferences.</li><li><strong>App and device information:</strong> app version, language, notification settings, security status and limited diagnostic information needed to operate and protect the service.</li><li><strong>Support information:</strong> details you choose to include when contacting support.</li></ul></section>
<section id="use"><h2>How information is used</h2><p>Information is used to provide app features, restore signed-in accounts, secure requests, calculate user-requested results, improve reliability, send enabled local notifications and answer support requests. We do not sell personal information.</p></section>
<section id="ai"><h2>Optional online AI</h2><p>Local assistant answers remain on the phone. Online Gemini is optional and is used only for eligible signed-in users after explicit consent. A limited financial summary and the question are sent for personalised assistance. Passwords, tokens, identity-document numbers, payment-card details and complete financial records are excluded. Consent can be withdrawn in the app. Gemini output is informational and may be inaccurate.</p></section>
<section id="sharing"><h2>Service providers</h2><p>Mera Markaz uses service providers such as Google Firebase for authentication, app protection and supported synchronisation; Google Gemini for consented online AI; and Meta for Facebook sign-in. Each provider processes information needed to deliver its service under its own terms and privacy practices.</p></section>
<section id="control"><h2>Your controls</h2><ul><li>Use guest mode for local-only activity.</li><li>Disable online AI and continue with local answers.</li><li>Edit profile information and notification preferences.</li><li>Sign out, remove local guest activity, or request account deletion.</li></ul></section>
<section id="security"><h2>Security and retention</h2><p>We use encryption, authenticated access and app-integrity controls appropriate to the service. No system is completely risk-free. Local guest information remains until the session is ended or app data is removed. Account information is retained while needed to provide the service or meet legal and security obligations, then deleted or de-identified as appropriate.</p></section>
<section id="contact"><h2>Contact</h2><p>For privacy questions or requests, use the support details published on the Mera Markaz Google Play listing or the <a className="text-link" href="/support">support page</a>. Confirm that your public support mailbox is active before publishing this policy.</p></section>
</DocumentShell>}
