import type { Metadata } from 'next';
import { DocumentShell } from '@/components/document-shell';
export const metadata: Metadata={title:'Delete your account',description:'Instructions for deleting a Mera Markaz account and associated data.'};
const sections=[{id:'inside',label:'Delete in the app'},{id:'request',label:'Request assistance'},{id:'deleted',label:'What is deleted'},{id:'retained',label:'What may remain'}];
export default function DeleteAccount(){return <DocumentShell kicker="Account control" title="Delete your Mera Markaz account" intro="You can start deletion from inside the app. If you cannot access your account, contact support using the official Google Play listing." sections={sections}>
<section id="inside"><h2>Delete from inside Mera Markaz</h2><ol className="steps"><li>Sign in to the account you want to delete.</li><li>Open your profile, then open Settings or Privacy &amp; security.</li><li>Select <strong>Delete account</strong>.</li><li>Review the warning, complete any required recent sign-in and confirm.</li></ol><div className="notice">Deletion is permanent. Export anything you need before confirming. Logging out or uninstalling the app does not by itself delete a signed-in account.</div></section>
<section id="request"><h2>If you cannot access the app</h2><p>Use the support email shown on the official Mera Markaz Google Play listing. Send the request from the email connected to your account, use the subject “Mera Markaz account deletion,” and do not include your password or verification codes. We may need to verify account ownership.</p></section>
<section id="deleted"><h2>Information scheduled for deletion</h2><p>The account profile and associated cloud-stored financial records, preferences and backup data are deleted or made inaccessible as part of the deletion process. Local app information can also be removed by clearing app storage or uninstalling after account deletion.</p></section>
<section id="retained"><h2>Limited information that may remain</h2><p>Limited records may be retained when reasonably necessary for security, fraud prevention, dispute resolution or legal obligations. Backups may take additional time to expire. Retained information is restricted and not used to provide the deleted account.</p></section>
</DocumentShell>}
