final urduPhrases = <String, String>{
  'OK': 'ٹھیک ہے',
  'Cancel': 'منسوخ',
  'Save': 'محفوظ کریں',
  'Saving…': 'محفوظ ہو رہا ہے…',
  'Delete': 'حذف کریں',
  'Edit': 'ترمیم',
  'Done': 'مکمل',
  'Date': 'تاریخ',
  'Try again': 'دوبارہ کوشش کریں',
  'Search': 'تلاش',
  'No matching local records.': 'کوئی مماثل مقامی ریکارڈ نہیں ملا۔',
  'Search your local records': 'اپنے مقامی ریکارڈ تلاش کریں',
  'Find expenses, income, people and Udhaar descriptions without uploading your data.':
      'اپنا ڈیٹا اپ لوڈ کیے بغیر خرچے، آمدنی، افراد اور ادھار کی تفصیل تلاش کریں۔',
  'Search expenses, income, people…': 'خرچے، آمدنی اور افراد تلاش کریں…',
  'Expenses & Income': 'خرچے اور آمدنی',
  'Expense': 'خرچہ',
  'Income': 'آمدنی',
  'Amount': 'رقم',
  'Description': 'تفصیل',
  'Payment method': 'ادائیگی کا طریقہ',
  'Note (optional)': 'نوٹ (اختیاری)',
  'Add transaction': 'لین دین شامل کریں',
  'Edit transaction': 'لین دین میں ترمیم',
  'Add entry for': 'اندراج شامل کریں برائے',
  'Delete transaction?': 'لین دین حذف کریں؟',
  'No transactions yet': 'ابھی کوئی لین دین نہیں',
  'Add income or an expense to begin your monthly overview.':
      'ماہانہ جائزہ شروع کرنے کے لیے آمدنی یا خرچہ شامل کریں۔',
  'Monthly income': 'ماہانہ آمدنی',
  'Monthly expenses': 'ماہانہ خرچے',
  'Today': 'آج',
  'This week': 'اس ہفتے',
  'Balance': 'بیلنس',
  'Enter a positive amount, description and category.':
      'مثبت رقم، تفصیل اور زمرہ درج کریں۔',
  'Cash': 'نقد',
  'Bank': 'بینک',
  'Card': 'کارڈ',
  'Other': 'دیگر',
  'Salary': 'تنخواہ',
  'Freelance': 'فری لانس',
  'Business': 'کاروبار',
  'Food': 'کھانا',
  'Grocery': 'کریانہ',
  'Shopping': 'خریداری',
  'Rent': 'کرایہ',
  'Education': 'تعلیم',
  'Health': 'صحت',
  'Entertainment': 'تفریح',
  'Travel': 'سفر',
  'Car': 'گاڑی',
  'Family': 'خاندان',
  'Udhaar / Khata': 'ادھار / کھاتہ',
  'New ledger': 'نیا کھاتہ',
  'No active ledgers': 'کوئی فعال کھاتہ نہیں',
  'Track money you gave or took without giving contact access.':
      'رابطوں کی اجازت دیے بغیر دی گئی یا لی گئی رقم کا حساب رکھیں۔',
  'You will receive': 'آپ کو وصول ہوگا',
  'You have to pay': 'آپ کو ادا کرنا ہے',
  'Record payment': 'ادائیگی درج کریں',
  'Record': 'درج کریں',
  'Store unavailable': 'اسٹور دستیاب نہیں',
  'English': 'انگریزی',
  'Delete ledger': 'کھاتہ حذف کریں',
  'Delete ledger?': 'کھاتہ حذف کریں؟',
  'All entries and repayment history for this person will be deleted.':
      'اس شخص کی تمام اندراجات اور ادائیگی کی تاریخ حذف ہو جائے گی۔',
  'Add entry': 'اندراج شامل کریں',
  'I gave': 'میں نے دیا',
  'I took': 'میں نے لیا',
  'Person name': 'شخص کا نام',
  'Phone (optional)': 'فون (اختیاری)',
  'Due date': 'واجب الادا تاریخ',
  'Receive': 'وصولی',
  'Pay': 'ادائیگی',
  'Notes (optional)': 'نوٹس (اختیاری)',
  'Save ledger': 'کھاتہ محفوظ کریں',
  'Pending': 'زیر التوا',
  'Part paid': 'جزوی ادا',
  'Paid': 'ادا شدہ',
  'Overdue': 'میعاد گزر گئی',
  'Budgets & Analytics': 'بجٹ اور تجزیات',
  'Monthly budget': 'ماہانہ بجٹ',
  'Budget amount': 'بجٹ کی رقم',
  'Payment amount': 'ادائیگی کی رقم',
  'MeraMarkaz Privacy Policy': 'میرا مرکز رازداری کی پالیسی',
  'MeraMarkaz Terms & Conditions': 'میرا مرکز شرائط و ضوابط',
  'Set budget': 'بجٹ مقرر کریں',
  'Delete budget?': 'بجٹ حذف کریں؟',
  'Enter an amount greater than zero.': 'صفر سے زیادہ رقم درج کریں۔',
  'Add an expense category first.': 'پہلے خرچے کا زمرہ شامل کریں۔',
  'Could not load budgets. Please try again.':
      'بجٹ لوڈ نہیں ہو سکے۔ دوبارہ کوشش کریں۔',
  'Something went wrong. Please try again.':
      'کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔',
  'Expense by category': 'زمرے کے لحاظ سے خرچہ',
  'Not set': 'مقرر نہیں',
  'remaining': 'باقی',
  'of': 'از',
  'Due': 'واجب الادا',
  'Add expenses to see category analytics.':
      'زمرہ وار تجزیہ دیکھنے کے لیے خرچے شامل کریں۔',
  'Export CSV': 'سی ایس وی برآمد کریں',
  'Export PDF': 'پی ڈی ایف برآمد کریں',
  'Export complete': 'برآمد مکمل',
  'Export failed': 'برآمد ناکام',
  'MeraMarkaz': 'میرا مرکز',
  'Everything you need. One place.': 'آپ کی ہر ضرورت، ایک جگہ۔',
  'Do more with your money': 'اپنی رقم سے مزید فائدہ اٹھائیں',
  'Budgets and analytics': 'بجٹ اور تجزیات',
  'PDF and CSV reports': 'پی ڈی ایف اور سی ایس وی رپورٹس',
  'Unlimited Udhaar ledgers': 'لامحدود ادھار کھاتے',
  'Saved calculations and history': 'محفوظ حساب اور تاریخ',
  'Terms': 'شرائط',
  'Privacy Policy': 'رازداری کی پالیسی',
  'Settings': 'ترتیبات',
  'Privacy & Data': 'رازداری اور ڈیٹا',
  'Notifications': 'اطلاعات',
  'Terms & Conditions': 'شرائط و ضوابط',
  'Language': 'زبان',
  'Appearance': 'ظاہری شکل',
  'System': 'سسٹم',
  'Light': 'روشن',
  'Dark': 'تاریک',
  'System default (Auto)': 'سسٹم ڈیفالٹ (خودکار)',
  'System default follows your phone appearance automatically.':
      'سسٹم ڈیفالٹ خودکار طور پر آپ کے فون کی ظاہری شکل کے مطابق چلتا ہے۔',
  'Local-first and private by default': 'مقامی اور بطور ڈیفالٹ نجی',
  'Data exported': 'ڈیٹا برآمد ہوگیا',
  'A complete JSON copy was saved locally:':
      'مکمل JSON نقل مقامی طور پر محفوظ ہوگئی:',
  'Delete all financial data?': 'تمام مالی ڈیٹا حذف کریں؟',
  'Delete everything': 'سب کچھ حذف کریں',
  'All financial data was deleted.': 'تمام مالی ڈیٹا حذف کردیا گیا۔',
  'Export all local data': 'تمام مقامی ڈیٹا برآمد کریں',
  'Create a human-readable JSON backup.': 'قابل مطالعہ JSON بیک اپ بنائیں۔',
  'Delete all financial data': 'تمام مالی ڈیٹا حذف کریں',
  'Permanent and cannot be undone.': 'یہ مستقل ہے اور واپس نہیں ہوسکتا۔',
  'Notification permission was not granted.': 'اطلاعات کی اجازت نہیں دی گئی۔',
  'Udhaar due dates': 'ادھار کی واجب الادا تاریخیں',
  'Budget thresholds': 'بجٹ کی حدیں',
  'Monthly expense summary': 'ماہانہ خرچ کا خلاصہ',
  'Yearly Zakat reminder': 'سالانہ زکوٰۃ یاد دہانی',
  'Recurring expenses': 'بار بار ہونے والے خرچے',
  'Electricity usage reminder': 'بجلی کے استعمال کی یاد دہانی',
  'Effective: 23 August 2026': 'مؤثر: 23 اگست 2026',
  'Local-first data': 'مقامی ڈیٹا',
  'Optional services': 'اختیاری خدمات',
  'Your controls': 'آپ کے اختیارات',
  'Estimates': 'تخمینے',
  'User responsibility': 'صارف کی ذمہ داری',
  'Your expenses, income, Udhaar records and saved calculations are stored locally on your device by default. You may use an account or continue offline. Account login may process your name, email address, provider identifier and basic provider profile. MeraMarkaz does not require CNIC, card details, contacts, SMS, call logs or location for its core features.':
      'آپ کے خرچے، آمدنی، ادھار ریکارڈ اور محفوظ حساب بطور ڈیفالٹ آپ کے آلے پر مقامی طور پر محفوظ ہوتے ہیں۔ آپ اکاؤنٹ استعمال کر سکتے ہیں یا آف لائن جاری رکھ سکتے ہیں۔ اکاؤنٹ لاگ اِن کے دوران آپ کا نام، ای میل پتہ، فراہم کنندہ شناخت اور بنیادی پروفائل استعمال ہو سکتا ہے۔ بنیادی سہولیات کے لیے پاک پاکٹ کو شناختی کارڈ، کارڈ کی تفصیل، رابطوں، ایس ایم ایس، کال لاگز یا مقام کی ضرورت نہیں۔',
  'Future production builds may use analytics, crash diagnostics and opt-in backup. The Play Store Data Safety form and this policy must be updated before those services are enabled.':
      'آئندہ پروڈکشن ورژن تجزیات، خرابی کی تشخیص اور اختیاری بیک اپ استعمال کر سکتے ہیں۔ ان خدمات کو فعال کرنے سے پہلے پلے اسٹور ڈیٹا سیفٹی فارم اور اس پالیسی کو اپ ڈیٹ کرنا ضروری ہے۔',
  'You can export your data and will be able to delete all locally stored data from Settings. Cloud backup, if introduced, will be explicit opt-in.':
      'آپ اپنا ڈیٹا برآمد کر سکتے ہیں اور ترتیبات سے تمام مقامی مالی ڈیٹا حذف کر سکتے ہیں۔ کلاؤڈ بیک اپ متعارف ہونے کی صورت میں واضح طور پر اختیاری ہوگا۔',
  'Tax, electricity, solar, property, fuel and Zakat results are informational estimates. They are not official bills, tax advice, legal advice, financial advice or religious rulings.':
      'ٹیکس، بجلی، سولر، جائیداد، ایندھن اور زکوٰۃ کے نتائج معلوماتی تخمینے ہیں۔ یہ سرکاری بل، ٹیکس، قانونی یا مالی مشورہ یا مذہبی فتویٰ نہیں ہیں۔',
  'You are responsible for checking inputs, current official rates and exported records before relying on a result.':
      'کسی نتیجے پر انحصار کرنے سے پہلے معلومات، موجودہ سرکاری نرخ اور برآمد شدہ ریکارڈ کی جانچ آپ کی ذمہ داری ہے۔',
  'Permission is requested only when you enable a reminder. Each reminder type can be disabled independently.':
      'اجازت صرف یاد دہانی فعال کرنے پر مانگی جاتی ہے۔ ہر یاد دہانی الگ سے بند کی جا سکتی ہے۔',
  'This permanently removes expenses, income, budgets, Udhaar ledgers, vehicles and saved calculations from this device. App preferences are retained. Export first if you need a copy.':
      'یہ اس آلے سے خرچے، آمدنی، بجٹ، ادھار کھاتے، گاڑیاں اور محفوظ حساب مستقل طور پر حذف کر دے گا۔ ایپ ترجیحات محفوظ رہیں گی۔ نقل درکار ہو تو پہلے برآمد کریں۔',
  'Your financial records stay in local app storage by default. No CNIC, login, contacts, SMS or location is required.':
      'آپ کے مالی ریکارڈ بطور ڈیفالٹ مقامی ایپ اسٹوریج میں رہتے ہیں۔ شناختی کارڈ، لاگ اِن، رابطوں، ایس ایم ایس یا مقام کی ضرورت نہیں۔',
  'Version 1.0.0 • Local-first and private by default':
      'ورژن 1.0.0 • مقامی اور بطور ڈیفالٹ نجی',
  'Your Money. Your Bills. Your Pakistan.':
      'آپ کی رقم۔ آپ کے بل۔ آپ کا پاکستان۔',
  'Welcome back': 'خوش آمدید',
  'Create your secure account': 'اپنا محفوظ اکاؤنٹ بنائیں',
  'Full name': 'پورا نام',
  'Enter your full name.': 'اپنا پورا نام درج کریں۔',
  'Email address': 'ای میل پتہ',
  'Enter a valid email address.': 'درست ای میل پتہ درج کریں۔',
  'Password': 'پاس ورڈ',
  'Password must be at least 6 characters.':
      'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔',
  'Confirm password': 'پاس ورڈ کی تصدیق',
  'Confirm your password.': 'اپنے پاس ورڈ کی تصدیق کریں۔',
  'Passwords do not match.': 'پاس ورڈ ایک جیسے نہیں ہیں۔',
  'Forgot password?': 'پاس ورڈ بھول گئے؟',
  'Enter your email first.': 'پہلے اپنا ای میل درج کریں۔',
  'Create account': 'اکاؤنٹ بنائیں',
  'Sign in': 'سائن اِن',
  'or continue with': 'یا اس کے ساتھ جاری رکھیں',
  'Continue with Google': 'گوگل کے ساتھ جاری رکھیں',
  'Continue with Facebook': 'فیس بک کے ساتھ جاری رکھیں',
  'Continue with Email': 'ای میل کے ساتھ جاری رکھیں',
  'New to Mera Markaz?': 'میرا مرکز پر نئے ہیں؟',
  'Create a new Account': 'نیا اکاؤنٹ بنائیں',
  'Sign In': 'سائن اِن',
  'Email Address': 'ای میل پتہ',
  "Don't have an account? Sign Up": 'اکاؤنٹ نہیں ہے؟ سائن اپ کریں',
  'Google': 'گوگل',
  'Facebook': 'فیس بک',
  'f': 'f',
  'Explore as Guest': 'بطور مہمان دریافت کریں',
  '© 2026 Mera Markaz Inc.': '© 2026 میرا مرکز',
  'Continue offline': 'آف لائن جاری رکھیں',
  'Continue as Guest': 'بطور مہمان جاری رکھیں',
  'Online sign-in requires Firebase configuration. Offline mode remains available.':
      'آن لائن سائن اِن کے لیے فائر بیس ترتیب ضروری ہے۔ آف لائن موڈ دستیاب ہے۔',
  'Already have an account? Sign in': 'پہلے سے اکاؤنٹ ہے؟ سائن اِن کریں',
  'New to MeraMarkaz? Create account': 'میرا مرکز پر نئے ہیں؟ اکاؤنٹ بنائیں',
  'Password reset email sent.': 'پاس ورڈ ری سیٹ ای میل بھیج دی گئی۔',
  'Firebase is not configured for this build.':
      'اس ورژن کے لیے فائر بیس ترتیب نہیں دیا گیا۔',
  'Email or password is incorrect.': 'ای میل یا پاس ورڈ غلط ہے۔',
  'An account already exists for this email.':
      'اس ای میل کے لیے اکاؤنٹ پہلے سے موجود ہے۔',
  'Use a stronger password with at least 6 characters.':
      'کم از کم 6 حروف والا مضبوط پاس ورڈ استعمال کریں۔',
  'Check your internet connection and try again.':
      'اپنا انٹرنیٹ کنکشن چیک کرکے دوبارہ کوشش کریں۔',
  'Too many attempts. Please try again later.':
      'بہت زیادہ کوششیں ہوئیں۔ بعد میں دوبارہ کوشش کریں۔',
  'This email already uses a different sign-in method.':
      'یہ ای میل پہلے ہی مختلف سائن اِن طریقہ استعمال کرتی ہے۔',
  'Authentication failed. Please try again.':
      'تصدیق ناکام ہوگئی۔ دوبارہ کوشش کریں۔',
  'Facebook sign-in was cancelled.': 'فیس بک سائن اِن منسوخ ہوگیا۔',
  'Sign out': 'سائن آؤٹ',
  'End this session on this device.': 'اس آلے پر یہ سیشن ختم کریں۔',
  'Edit profile': 'پروفائل میں ترمیم',
  'Complete your profile': 'اپنا پروفائل مکمل کریں',
  'Profile unavailable': 'پروفائل دستیاب نہیں',
  'Profile completion': 'پروفائل کی تکمیل',
  'Personal information': 'ذاتی معلومات',
  'Preferences': 'ترجیحات',
  'Account & app': 'اکاؤنٹ اور ایپ',
  'Keep your details up to date for a more personal experience.':
      'بہتر ذاتی تجربے کے لیے اپنی معلومات تازہ رکھیں۔',
  'Phone number': 'فون نمبر',
  'Province / Region': 'صوبہ / علاقہ',
  'City': 'شہر',
  'Occupation': 'پیشہ',
  'Save changes': 'تبدیلیاں محفوظ کریں',
  'Temporary guest session': 'عارضی مہمان سیشن',
  'Create an account to keep your current activity. Sign in to an existing account to discard this temporary activity and restore that account.':
      'اپنی موجودہ سرگرمی محفوظ رکھنے کے لیے اکاؤنٹ بنائیں۔ موجودہ اکاؤنٹ میں سائن اِن کرنے پر عارضی سرگرمی حذف ہو جائے گی اور اس اکاؤنٹ کا ڈیٹا بحال ہوگا۔',
  'Create account & keep data': 'اکاؤنٹ بنائیں اور ڈیٹا محفوظ رکھیں',
  'Sign in to existing account': 'موجودہ اکاؤنٹ میں سائن اِن کریں',
  'Add Expense': 'خرچہ شامل کریں',
  'Add Udhaar': 'ادھار شامل کریں',
  'Calculate Tax': 'ٹیکس حساب کریں',
  'Calculate Bill': 'بل حساب کریں',
  'Fuel': 'ایندھن',
  'Zakat': 'زکوٰۃ',
  'Salary Tax': 'تنخواہ ٹیکس',
  'Salary tax': 'تنخواہ ٹیکس',
  'FBR-ready estimate': 'ایف بی آر کے مطابق تخمینہ',
  'Electricity Bill': 'بجلی کا بل',
  'Estimate your bill': 'اپنے بل کا تخمینہ',
  'Solar Calculator': 'سولر کیلکولیٹر',
  'Plan your system': 'اپنے سسٹم کی منصوبہ بندی',
  'Plot / Marla': 'پلاٹ / مرلہ',
  'Convert property area': 'جائیداد کا رقبہ تبدیل کریں',
  'TOTAL MONTHLY EXPENSES': 'کل ماہانہ خرچے',
  'Mera Markaz User': 'میرا مرکز صارف',
  'Gain deeper insights into your spending habits.':
      'اپنے خرچ کی عادات کے بارے میں مزید معلومات حاصل کریں۔',
  'MY ACCOUNT': 'میرا اکاؤنٹ',
  'Edit Profile': 'پروفائل میں ترمیم',
  'FINANCIAL SETTINGS': 'مالی ترتیبات',
  'Default Currency': 'بنیادی کرنسی',
  'Tax Year': 'ٹیکس سال',
  'Marla Standard': 'مرلہ معیار',
  'SECURITY': 'سیکیورٹی',
  'Biometric Lock': 'بایومیٹرک لاک',
  'Data Privacy': 'ڈیٹا رازداری',
  'SUPPORT & DATA': 'مدد اور ڈیٹا',
  'Rate App': 'ایپ کو ریٹ کریں',
  'Share Mera Markaz': 'میرا مرکز شیئر کریں',
  'Help Center': 'مدد مرکز',
  'Export Data (CSV/PDF)': 'ڈیٹا برآمد کریں (CSV/PDF)',
  'Delete All Data': 'تمام ڈیٹا حذف کریں',
  'Back': 'واپس',
  'Close': 'بند کریں',
  'Mark all as read': 'سب کو پڑھا ہوا نشان زد کریں',
  'Monthly summary': 'ماہانہ خلاصہ',
  'Your latest financial summary is ready.': 'آپ کا تازہ مالی خلاصہ تیار ہے۔',
  'Udhaar reminders': 'ادھار کی یاد دہانیاں',
  'Upcoming Udhaar due dates will appear here.':
      'آنے والی ادھار کی تاریخیں یہاں نظر آئیں گی۔',
  'Account security': 'اکاؤنٹ سیکیورٹی',
  'Keep biometric lock enabled for extra security.':
      'اضافی حفاظت کے لیے بایومیٹرک لاک فعال رکھیں۔',
  'Fingerprint authentication is not available on this device.':
      'اس آلے پر فنگرپرنٹ تصدیق دستیاب نہیں ہے۔',
  'Mera Markaz is locked': 'میرا مرکز لاک ہے',
  'Use your fingerprint to securely continue.':
      'محفوظ طریقے سے جاری رکھنے کے لیے فنگرپرنٹ استعمال کریں۔',
  'Unlock with fingerprint': 'فنگرپرنٹ سے کھولیں',
  'Sign in with fingerprint': 'فنگرپرنٹ سے سائن اِن کریں',
  'User': 'صارف',
  'PKR': 'PKR',
  '2024–25': '2024–25',
  '225 sq ft': '225 مربع فٹ',
  'sq ft': 'مربع فٹ',
  'Select tax year': 'ٹیکس سال منتخب کریں',
  'Pakistan tax years run from 1 July to 30 June. Calculator rates change when a new Finance Act takes effect.':
      'پاکستان میں ٹیکس سال یکم جولائی سے 30 جون تک ہوتا ہے۔ نئے فنانس ایکٹ کے نافذ ہونے پر کیلکولیٹر کے نرخ بدل جاتے ہیں۔',
  'Current • FBR Finance Act 2026': 'موجودہ • ایف بی آر فنانس ایکٹ 2026',
  'FBR Finance Act 2025': 'ایف بی آر فنانس ایکٹ 2025',
  'Select Marla standard': 'مرلہ معیار منتخب کریں',
  'Marla size varies by authority and housing society. Confirm it from the approved plan or property documents.':
      'مرلے کا سائز اتھارٹی اور ہاؤسنگ سوسائٹی کے لحاظ سے مختلف ہوتا ہے۔ منظور شدہ نقشے یا جائیداد کے کاغذات سے تصدیق کریں۔',
  'Lahore and many modern housing schemes':
      'لاہور اور بہت سی جدید ہاؤسنگ اسکیمیں',
  'Used by some housing societies': 'کچھ ہاؤسنگ سوسائٹیوں میں استعمال ہوتا ہے',
  'Traditional standard and ICT': 'روایتی معیار اور اسلام آباد',
  'Enter custom size': 'اپنا سائز درج کریں',
  'Custom Marla size': 'اپنی مرضی کا مرلہ سائز',
  'Square feet per Marla': 'فی مرلہ مربع فٹ',
  'Punjab': 'پنجاب',
  'Sindh': 'سندھ',
  'Khyber Pakhtunkhwa': 'خیبر پختونخوا',
  'Balochistan': 'بلوچستان',
  'Islamabad Capital Territory': 'اسلام آباد وفاقی علاقہ',
  'Gilgit-Baltistan': 'گلگت بلتستان',
  'Azad Jammu & Kashmir': 'آزاد جموں و کشمیر',
  'Unknown calculator': 'نامعلوم کیلکولیٹر',
  'Annual income': 'سالانہ آمدنی',
  'Annual tax': 'سالانہ ٹیکس',
  'Monthly tax': 'ماہانہ ٹیکس',
  'Monthly take-home': 'ماہانہ خالص تنخواہ',
  'Effective rate': 'مؤثر شرح',
  'Energy charges': 'توانائی کے چارجز',
  'Fixed charges': 'مقررہ چارجز',
  'Taxes/adjustments': 'ٹیکس/ایڈجسٹمنٹ',
  'Estimated total': 'تخمینی کل',
  'Recommended size': 'تجویز کردہ سائز',
  'Monthly generation': 'ماہانہ پیداوار',
  'Roof required': 'درکار چھت',
  'Monthly savings': 'ماہانہ بچت',
  'Payback estimate': 'واپسی کا تخمینہ',
  'Square feet': 'مربع فٹ',
  'Square yards': 'مربع گز',
  'Marla': 'مرلہ',
  'Kanal': 'کنال',
  'Square meters': 'مربع میٹر',
  'Estimated price': 'تخمینی قیمت',
  'Fuel average': 'ایندھن اوسط',
  'Fuel cost': 'ایندھن لاگت',
  'Net Zakatable': 'خالص قابل زکوٰۃ',
  'Nisab threshold': 'نصاب کی حد',
  'Zakat due?': 'کیا زکوٰۃ واجب ہے؟',
  'Estimated Zakat': 'تخمینی زکوٰۃ',
  'Yes': 'ہاں',
  'No': 'نہیں',
  'Add Income': 'آمدنی شامل کریں',
  'Ask Markaz AI': 'مرکز اے آئی سے پوچھیں',
  'Markaz AI': 'مرکز اے آئی',
  'Send Feedback': 'رائے بھیجیں',
  'Help us improve Mera Markaz': 'میرا مرکز کو بہتر بنانے میں مدد کریں',
  'Share a suggestion, report a problem, or tell us what you would like to see next.':
      'کوئی تجویز دیں، مسئلہ رپورٹ کریں یا بتائیں کہ آپ آگے کیا دیکھنا چاہتے ہیں۔',
  'Send anonymously': 'گمنام طور پر بھیجیں',
  'Your name and phone number will not be included.':
      'آپ کا نام اور فون نمبر شامل نہیں کیا جائے گا۔',
  'Name (optional)': 'نام (اختیاری)',
  'Phone number (optional)': 'فون نمبر (اختیاری)',
  'Your message': 'آپ کا پیغام',
  'Describe your suggestion or the issue you experienced…':
      'اپنی تجویز یا پیش آنے والے مسئلے کی وضاحت کریں…',
  'Please enter at least 10 characters.': 'کم از کم 10 حروف درج کریں۔',
  'Do not include passwords, verification codes, card details, CNIC numbers, or other sensitive information.':
      'پاس ورڈ، تصدیقی کوڈ، کارڈ کی تفصیلات، شناختی کارڈ نمبر یا دیگر حساس معلومات شامل نہ کریں۔',
  'Sending…': 'بھیجا جا رہا ہے…',
  'Thank you. Your feedback has been sent.':
      'شکریہ۔ آپ کی رائے بھیج دی گئی ہے۔',
  'Feedback could not be sent.': 'رائے نہیں بھیجی جا سکی۔',
  'Could not contact the feedback service. Check your internet connection and try again.':
      'فیڈبیک سروس سے رابطہ نہیں ہو سکا۔ انٹرنیٹ کنکشن چیک کر کے دوبارہ کوشش کریں۔',
  'Enter the current total reading shown on the vehicle.':
      'گاڑی پر دکھائی جانے والی موجودہ کل اوڈومیٹر ریڈنگ درج کریں۔',
  'Enter a vehicle name and a valid odometer.':
      'گاڑی کا نام اور درست اوڈومیٹر درج کریں۔',
  'Vehicle could not be saved. Please try again.':
      'گاڑی محفوظ نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
  'Protected residential consumer': 'محفوظ رہائشی صارف',
  'Enable only if “Protected” appears on your electricity bill.':
      'صرف اسی وقت فعال کریں جب آپ کے بجلی کے بل پر “Protected” لکھا ہو۔',
  'Protected or non-protected status': 'محفوظ یا غیر محفوظ حیثیت',
  'Electricity duty': 'بجلی ڈیوٹی',
  'FCA, QTA and other adjustments': 'FCA، QTA اور دیگر ایڈجسٹمنٹ',
  'TV fee': 'ٹی وی فیس',
  'Tariff category': 'ٹیرف کی قسم',
  'FCA/QTA/other adjustments': 'FCA/QTA/دیگر ایڈجسٹمنٹ',
  'Essential backup load': 'ضروری بیک اپ لوڈ',
  'Required backup time': 'درکار بیک اپ وقت',
  'Panel quality checklist': 'سولر پینل معیار کی فہرست',
  'Inverter and protection checklist': 'انورٹر اور حفاظتی فہرست',
  'Battery sizing': 'بیٹری کا سائز',
  'Suggested inverter': 'تجویز کردہ انورٹر',
  'Usable battery energy': 'قابل استعمال بیٹری توانائی',
  'Lithium battery bank (80% DoD)': 'لیتھیم بیٹری بینک (80% DoD)',
  'Panels (585 W)': 'پینلز (585 واٹ)',
  'Common Marla standard': 'عام مرلہ معیار',
  '225 sq ft — Lahore convention': '225 مربع فٹ — لاہور کا رواج',
  '250 sq ft — some societies': '250 مربع فٹ — بعض ہاؤسنگ سوسائٹیز',
  '272.25 sq ft — ICT/traditional': '272.25 مربع فٹ — اسلام آباد/روایتی',
  'Verify before buying': 'خریدنے سے پہلے تصدیق کریں',
  'Acres': 'ایکڑ',
  'Consumption': 'کھپت',
  'Tax before surcharge': 'سرچارج سے پہلے ٹیکس',
  '9% high-income surcharge': 'زیادہ آمدنی پر 9% سرچارج',
  'Tax Year 2027 / FY 2026-27': 'ٹیکس سال 2027 / مالی سال 2026-27',
  'Select protected only when your bill identifies you as protected. NEPRA defines this around sustained low residential consumption; the status is determined by your billing history, not only this month’s units.':
      'محفوظ صارف صرف تب منتخب کریں جب آپ کے بل پر یہی حیثیت درج ہو۔ NEPRA اسے مسلسل کم رہائشی کھپت کی بنیاد پر متعین کرتا ہے؛ یہ حیثیت صرف موجودہ ماہ کے یونٹس سے نہیں بلکہ بلنگ ہسٹری سے طے ہوتی ہے۔',
  'Monthly FCA/QTA, subsidies, arrears and provider-specific adjustments are not a stable per-unit tariff. Copy their combined amount from the applicable notification or bill into the adjustment field for a closer estimate.':
      'ماہانہ FCA/QTA، سبسڈی، بقایا جات اور کمپنی کی مخصوص ایڈجسٹمنٹ مستقل فی یونٹ ٹیرف نہیں ہیں۔ زیادہ درست تخمینے کے لیے متعلقہ نوٹیفکیشن یا بل سے ان کی مجموعی رقم ایڈجسٹمنٹ والے خانے میں درج کریں۔',
  'Prefer verifiable Tier-1 bankable manufacturers, N-type mono modules with documented IEC 61215 and IEC 61730 compliance, a traceable serial number, product warranty and linear performance warranty. Tier-1 describes manufacturer bankability, not an automatic quality guarantee.':
      'قابل تصدیق Tier-1 مینوفیکچرر، N-type مونو ماڈیول، IEC 61215 اور IEC 61730 کی دستاویزی تعمیل، قابل سراغ سیریل نمبر، پروڈکٹ وارنٹی اور لینیئر پرفارمنس وارنٹی کو ترجیح دیں۔ Tier-1 صرف مینوفیکچرر کی مالی اہلیت بتاتا ہے، خودکار معیار کی ضمانت نہیں۔',
  'The inverter must support the panel string voltage/current, provide suitable MPPT inputs, anti-islanding and applicable grid protection. Ask for DC isolators, correctly rated breakers, surge protection, earthing and a licensed installer. Confirm the current DISCO and NEPRA prosumer rules before planning export.':
      'انورٹر کو پینل اسٹرنگ کا وولٹیج اور کرنٹ، مناسب MPPT، اینٹی آئی لینڈنگ اور متعلقہ گرڈ تحفظ سپورٹ کرنا چاہیے۔ DC آئسولیٹر، درست ریٹنگ کے بریکر، سرج پروٹیکشن، ارتھنگ اور لائسنس یافتہ انسٹالر لازماً طلب کریں۔ گرڈ کو بجلی دینے سے پہلے موجودہ DISCO اور NEPRA پروزیومر قواعد کی تصدیق کریں۔',
  'Enter only essential simultaneous load and desired backup hours. The tool estimates usable energy and allows 20% reserve for a lithium battery. Lead-acid systems normally require a larger nominal bank and different depth-of-discharge assumptions.':
      'صرف ضروری بیک وقت لوڈ اور مطلوبہ بیک اپ گھنٹے درج کریں۔ یہ ٹول قابل استعمال توانائی کا تخمینہ لگاتا اور لیتھیم بیٹری کے لیے 20% محفوظ گنجائش رکھتا ہے۔ لیڈ ایسڈ سسٹم کے لیے عموماً بڑا بیٹری بینک اور مختلف ڈسچارج مفروضہ درکار ہوتا ہے۔',
  'This converts area only; it does not verify ownership, approved layout, zoning, road width, possession, encumbrances or buildable area. Match the Marla definition and dimensions against the allotment letter, approved map and relevant development authority record.':
      'یہ صرف رقبہ تبدیل کرتا ہے؛ ملکیت، منظور شدہ لے آؤٹ، زوننگ، سڑک کی چوڑائی، قبضہ، قانونی بوجھ یا قابل تعمیر رقبے کی تصدیق نہیں کرتا۔ مرلہ کی تعریف اور ابعاد کو الاٹمنٹ لیٹر، منظور شدہ نقشے اور متعلقہ ڈویلپمنٹ اتھارٹی کے ریکارڈ سے ملائیں۔',
  'Monthly salary is converted to annual taxable income and the progressive salaried-individual slabs for the selected FBR tax year are applied. For taxable income above Rs. 10 million, the calculator adds the applicable 9% surcharge on computed income tax.':
      'ماہانہ تنخواہ کو سالانہ قابل ٹیکس آمدنی میں تبدیل کر کے منتخب FBR ٹیکس سال کے تنخواہ دار افراد کے تدریجی سلیب لاگو کیے جاتے ہیں۔ ایک کروڑ روپے سے زائد قابل ٹیکس آمدنی پر حساب شدہ انکم ٹیکس میں متعلقہ 9% سرچارج شامل کیا جاتا ہے۔',
  'The selected FY 2026-27 configuration is Tax Year 2027 under FBR naming. It uses the Finance Act 2026 salaried slabs and identifies the source/version in every result.':
      'منتخب مالی سال 2026-27 کو FBR کے مطابق ٹیکس سال 2027 کہا جاتا ہے۔ اس میں فنانس ایکٹ 2026 کے تنخواہ دار سلیب استعمال ہوتے ہیں اور ہر نتیجے میں ماخذ اور ورژن درج ہوتا ہے۔',
  'Enter taxable salary, not gross reimbursements. Exempt allowances, tax credits, employer adjustments, pension treatment, foreign income and income under other heads require their own legal treatment and may change the final return.':
      'قابل ٹیکس تنخواہ درج کریں، مجموعی اخراجات کی واپسی نہیں۔ مستثنیٰ الاؤنس، ٹیکس کریڈٹ، آجر کی ایڈجسٹمنٹ، پنشن، غیر ملکی آمدنی اور دیگر ذرائع کی آمدنی کا الگ قانونی طریقہ ہوتا ہے اور حتمی ریٹرن بدل سکتا ہے۔',
  'New chat': 'نئی گفتگو',
  'Your chats': 'آپ کی گفتگوئیں',
  'Search chats': 'گفتگو تلاش کریں',
  'No chats found': 'کوئی گفتگو نہیں ملی',
  'Rename chat': 'گفتگو کا نام بدلیں',
  'Chat title': 'گفتگو کا عنوان',
  'Delete chat': 'گفتگو حذف کریں',
  'Delete chat?': 'گفتگو حذف کریں؟',
  'This chat and its messages will be permanently deleted from this device.':
      'یہ گفتگو اور اس کے پیغامات اس ڈیوائس سے مستقل طور پر حذف ہو جائیں گے۔',
  "Keep using Mera Markaz and we'll show insights as your financial history grows.":
      'میرا مرکز استعمال کرتے رہیں، مالی تاریخ بڑھنے پر ہم مفید بصیرت دکھائیں گے۔',
  'Your largest expense category this month is':
      'اس ماہ آپ کے خرچ کی سب سے بڑی قسم ہے',
  'Deterministic questions are calculated locally. External AI will require explicit consent.':
      'واضح مالی سوالات کا حساب مقامی طور پر ہوتا ہے۔ بیرونی اے آئی کے لیے واضح اجازت درکار ہوگی۔',
  'Show amounts': 'رقوم دکھائیں',
  'Hide amounts': 'رقوم چھپائیں',
  'Recent transactions': 'حالیہ لین دین',
  'AVAILABLE BALANCE': 'دستیاب بیلنس',
  'Expenses are unchanged from last month': 'خرچے پچھلے ماہ کے برابر ہیں',
  'expenses vs last month': 'خرچے بمقابلہ پچھلا ماہ',
  'Expenses': 'خرچے',
  'Budget exceeded': 'بجٹ سے تجاوز',
  'Spent': 'خرچ',
  'View all transactions': 'تمام لین دین دیکھیں',
  'Financial summary unavailable': 'مالی خلاصہ دستیاب نہیں',
  'Your records are safe. Try loading the summary again.':
      'آپ کے ریکارڈ محفوظ ہیں۔ خلاصہ دوبارہ لوڈ کرنے کی کوشش کریں۔',
  'Retry': 'دوبارہ کوشش کریں',
  'budget warning': 'بجٹ انتباہ',
  "You've used": 'آپ نے استعمال کر لیا ہے',
  'of your monthly budget.': 'اپنے ماہانہ بجٹ کا۔',
  'of your': 'اپنے',
  'budget.': 'بجٹ کا۔',
  'Category budget': 'زمرہ بجٹ',
  'Budget warnings': 'بجٹ انتباہات',
  'Category budgets': 'زمرہ وار بجٹ',
  'Add': 'شامل کریں',
  'No category budgets yet': 'ابھی کوئی زمرہ بجٹ نہیں',
  'Set limits for categories such as Food, Fuel or Shopping.':
      'خوراک، ایندھن یا خریداری جیسے زمروں کے لیے حد مقرر کریں۔',
  'Budget exceeded by': 'بجٹ سے تجاوز کی رقم',
  'Savings': 'بچت',
  'Savings goals': 'بچت کے اہداف',
  'Create goal': 'ہدف بنائیں',
  'No savings goals yet': 'ابھی کوئی بچت ہدف نہیں',
  "Create a goal for something you're working toward.":
      'جس چیز کے لیے آپ کوشش کر رہے ہیں اس کا ہدف بنائیں۔',
  'Create a goal and start tracking progress.':
      'ہدف بنائیں اور پیش رفت ریکارڈ کرنا شروع کریں۔',
  'View all': 'سب دیکھیں',
  'Remaining': 'باقی',
  'Withdraw savings': 'بچت نکالیں',
  'Add contribution': 'بچت شامل کریں',
  'Confirm': 'تصدیق کریں',
  'Withdrawal exceeds the saved amount.':
      'نکالی جانے والی رقم محفوظ بچت سے زیادہ ہے۔',
  'Archived goals cannot be changed.': 'محفوظ شدہ ہدف تبدیل نہیں ہو سکتا۔',
  'Edit goal': 'ہدف میں ترمیم',
  'Complete goal': 'ہدف مکمل کریں',
  'Archive goal': 'ہدف محفوظ کریں',
  'complete': 'مکمل',
  'Contribute': 'بچت شامل کریں',
  'Withdraw': 'نکالیں',
  'Savings forecast': 'بچت کی پیش گوئی',
  'Add more contribution history to estimate completion.':
      'تکمیل کا تخمینہ لگانے کے لیے مزید بچت ریکارڈ کریں۔',
  'Estimated time at your current rate': 'موجودہ رفتار پر تخمینی وقت',
  'months': 'ماہ',
  'Required monthly saving': 'درکار ماہانہ بچت',
  'Forecasts are estimates based on recorded contributions.':
      'پیش گوئیاں ریکارڈ شدہ بچت کی بنیاد پر تخمینے ہیں۔',
  'Contribution history': 'بچت کی تاریخ',
  'No contributions recorded yet.': 'ابھی کوئی بچت ریکارڈ نہیں ہوئی۔',
  'Goal name': 'ہدف کا نام',
  'Target amount': 'ہدف کی رقم',
  'Target date': 'ہدف کی تاریخ',
  'Optional': 'اختیاری',
  'Save goal': 'ہدف محفوظ کریں',
  'Show archived goals': 'محفوظ شدہ اہداف دکھائیں',
  'Hide archived goals': 'محفوظ شدہ اہداف چھپائیں',
  'Restore goal': 'ہدف بحال کریں',
  'Markaz Insight': 'مرکز بصیرت',
  'AI privacy': 'اے آئی رازداری',
  'These answers are calculated on your device. No financial data is sent to an external AI service. External AI will require separate consent and a secure backend.':
      'یہ جوابات آپ کے آلے پر حساب کیے جاتے ہیں۔ کوئی مالی ڈیٹا بیرونی اے آئی سروس کو نہیں بھیجا جاتا۔ بیرونی اے آئی کے لیے الگ اجازت اور محفوظ بیک اینڈ درکار ہوگا۔',
  'Try asking': 'یہ سوال پوچھیں',
  'Analyze my spending': 'میرے خرچ کا تجزیہ کریں',
  'Compare this month': 'اس ماہ کا موازنہ کریں',
  'Where can I save?': 'میں کہاں بچت کر سکتا ہوں؟',
  'Show my biggest expenses': 'میرے سب سے بڑے خرچے دکھائیں',
  'Check my budget': 'میرا بجٹ چیک کریں',
  'Summarize my Udhaar': 'میرے ادھار کا خلاصہ دیں',
  'Analyze my fuel spending': 'میرے ایندھن کے خرچ کا تجزیہ کریں',
  'Ask a question about your locally recorded finances.':
      'اپنے مقامی طور پر ریکارڈ شدہ مالیات کے بارے میں سوال پوچھیں۔',
  'Ask Markaz AI…': 'مرکز اے آئی سے پوچھیں…',
  'Markaz Score': 'مرکز اسکور',
  'Excellent': 'بہترین',
  'Good': 'اچھا',
  'Fair': 'مناسب',
  'Needs attention': 'توجہ درکار',
  'Not enough data': 'ناکافی ڈیٹا',
  'This is a personal wellness indicator, not a credit score or financial certification.':
      'یہ ذاتی مالی صحت کا اشارہ ہے، کریڈٹ اسکور یا مالی تصدیق نہیں۔',
  'Improve your score': 'اپنا اسکور بہتر کریں',
  'Smart insights': 'سمارٹ بصیرت',
  'Good savings rate': 'اچھی بچت کی شرح',
  'Low savings rate': 'کم بچت کی شرح',
  'Expenses are controlled': 'خرچے قابو میں ہیں',
  'Expenses are high compared with income':
      'آمدنی کے مقابلے میں خرچے زیادہ ہیں',
  'No category budgets configured': 'کوئی زمرہ بجٹ ترتیب نہیں دیا گیا',
  'Staying within category budgets': 'زمرہ بجٹ کی حدود میں ہیں',
  'Some category budgets are exceeded': 'کچھ زمرہ بجٹ حد سے بڑھ گئے ہیں',
  'No outstanding Udhaar payable': 'کوئی قابل ادائیگی ادھار باقی نہیں',
  'Outstanding Udhaar payable': 'قابل ادائیگی ادھار باقی ہے',
  'Savings reserve recorded': 'بچت کا ذخیرہ ریکارڈ ہے',
  'Limited savings reserve': 'بچت کا ذخیرہ محدود ہے',
  'Spending is relatively consistent': 'خرچ نسبتاً مستقل ہے',
  'Spending changed significantly': 'خرچ میں نمایاں تبدیلی آئی',
  'Work toward saving at least 10% of recorded income.':
      'ریکارڈ شدہ آمدنی کا کم از کم 10 فیصد بچانے کی کوشش کریں۔',
  'Reduce expenses relative to recorded monthly income.':
      'ریکارڈ شدہ ماہانہ آمدنی کے مقابلے میں خرچے کم کریں۔',
  'Set category budgets to improve spending control.':
      'خرچ پر قابو بہتر کرنے کے لیے زمرہ بجٹ بنائیں۔',
  'Bring exceeded categories back within budget.':
      'حد سے بڑھے زمروں کو دوبارہ بجٹ میں لائیں۔',
  'Reduce outstanding Udhaar payable where practical.':
      'جہاں ممکن ہو قابل ادائیگی ادھار کم کریں۔',
  'Build savings equal to at least one month of expenses.':
      'کم از کم ایک ماہ کے خرچ کے برابر بچت بنائیں۔',
  'Record income and expenses to calculate your Markaz Score.':
      'مرکز اسکور کے حساب کے لیے آمدنی اور خرچے ریکارڈ کریں۔',
  'Financial timeline': 'مالی ٹائم لائن',
  'Recurring transactions': 'بار بار ہونے والے لین دین',
  'Search timeline': 'ٹائم لائن تلاش کریں',
  'income': 'آمدنی',
  'expense': 'خرچہ',
  'udhaar': 'ادھار',
  'savings': 'بچت',
  'Date range': 'تاریخ کی حد',
  'Amount range': 'رقم کی حد',
  'Minimum amount': 'کم از کم رقم',
  'Maximum amount': 'زیادہ سے زیادہ رقم',
  'Clear': 'صاف کریں',
  'Apply': 'لاگو کریں',
  'No timeline entries found.': 'کوئی ٹائم لائن اندراج نہیں ملا۔',
  'Withdrawal': 'نکالی گئی رقم',
  'Contribution': 'بچت',
  'Recurring transaction': 'بار بار ہونے والا لین دین',
  'Frequency': 'تکرار',
  'weekly': 'ہفتہ وار',
  'monthly': 'ماہانہ',
  'customDays': 'مخصوص دن',
  'Next due date': 'اگلی واجب تاریخ',
  'Add recurring': 'بار بار لین دین شامل کریں',
  'No recurring transactions yet.': 'ابھی کوئی بار بار ہونے والا لین دین نہیں۔',
  'Pause': 'روکیں',
  'Resume': 'دوبارہ شروع کریں',
  'Upcoming reminder': 'آنے والی یاد دہانی',
  'My vehicles': 'میری گاڑیاں',
  'Add vehicle': 'گاڑی شامل کریں',
  'Track fuel, mileage and maintenance in one place.':
      'ایندھن، مائلیج اور دیکھ بھال ایک جگہ ریکارڈ کریں۔',
  'Add your first vehicle': 'اپنی پہلی گاڑی شامل کریں',
  'Vehicle name': 'گاڑی کا نام',
  'Make and model': 'کمپنی اور ماڈل',
  'Current odometer': 'موجودہ اوڈومیٹر',
  'Fuel spent': 'ایندھن کا خرچ',
  'Average mileage': 'اوسط مائلیج',
  'Cost per km': 'فی کلومیٹر لاگت',
  'Maintenance': 'دیکھ بھال',
  'Add fuel': 'ایندھن شامل کریں',
  'Add service': 'سروس شامل کریں',
  'Fuel history': 'ایندھن کی ہسٹری',
  'No fuel entries yet.': 'ابھی ایندھن کا کوئی اندراج نہیں۔',
  'Maintenance history': 'دیکھ بھال کی ہسٹری',
  'No maintenance entries yet.': 'ابھی دیکھ بھال کا کوئی اندراج نہیں۔',
  'Next': 'اگلی',
  'Save and add expense': 'محفوظ کریں اور خرچ شامل کریں',
  'Add maintenance': 'دیکھ بھال شامل کریں',
  'Service type': 'سروس کی قسم',
  'Cost': 'لاگت',
  'Remind me after days (optional)': 'اتنے دن بعد یاد دلائیں (اختیاری)',
  'Liters': 'لیٹر',
  'Total cost': 'کل لاگت',
  'Odometer': 'اوڈومیٹر',
  'Salary added to income. Saving again will update this entry.':
      'تنخواہ آمدنی میں شامل ہوگئی۔ دوبارہ محفوظ کرنے سے یہی اندراج اپ ڈیٹ ہوگا۔',
  'Electricity bill added to expenses.': 'بجلی کا بل خرچوں میں شامل ہوگیا۔',
  'Fuel purchase added to expenses.': 'ایندھن کی خریداری خرچوں میں شامل ہوگئی۔',
  'Smart finance tools': 'سمارٹ مالیاتی اوزار',
  'Receipt scanner': 'رسید اسکینر',
  'Scan, review and confirm receipt expenses':
      'رسید اسکین کریں، جانچیں اور خرچے کی تصدیق کریں',
  'Voice entry': 'آواز سے اندراج',
  'Speak a short income or expense entry':
      'آمدنی یا خرچہ مختصر بول کر درج کریں',
  'Reports': 'رپورٹس',
  'Generate local PDF and CSV reports': 'مقامی PDF اور CSV رپورٹس بنائیں',
  'Net worth': 'خالص مالیت',
  'Track assets and liabilities': 'اثاثے اور واجبات ریکارڈ کریں',
  'Could not scan receipt': 'رسید اسکین نہیں ہو سکی',
  'Review receipt': 'رسید کی جانچ',
  'Merchant': 'دکاندار',
  'Total': 'کل',
  'Category': 'زمرہ',
  'Please verify scanned details before saving.':
      'محفوظ کرنے سے پہلے اسکین شدہ تفصیلات کی تصدیق کریں۔',
  'Confirm expense': 'خرچے کی تصدیق کریں',
  'Receipt data stays on this device. Always review OCR results.':
      'رسید کا ڈیٹا اسی ڈیوائس پر رہتا ہے۔ OCR نتیجہ لازماً جانچیں۔',
  'Take photo': 'تصویر لیں',
  'Choose from gallery': 'گیلری سے منتخب کریں',
  'Speech recognition is unavailable.': 'آواز کی شناخت دستیاب نہیں۔',
  'Say a description and amount, for example: groceries 2500.':
      'تفصیل اور رقم بولیں، مثال: راشن 2500۔',
  'Transaction saved.': 'لین دین محفوظ ہو گیا۔',
  'Tap the microphone and speak a short transaction.':
      'مائیک دبائیں اور مختصر لین دین بولیں۔',
  'Review and save': 'جانچیں اور محفوظ کریں',
  'Report created': 'رپورٹ بن گئی',
  'PDF financial report': 'PDF مالیاتی رپورٹ',
  'Monthly summary and transaction history':
      'ماہانہ خلاصہ اور لین دین کی ہسٹری',
  'CSV transaction export': 'CSV لین دین ایکسپورٹ',
  'Spreadsheet-ready transaction data': 'اسپریڈشیٹ کے لیے تیار لین دین ڈیٹا',
  'Add account': 'اکاؤنٹ شامل کریں',
  'Estimated net worth': 'تخمینی خالص مالیت',
  'Assets': 'اثاثے',
  'Liabilities': 'واجبات',
  'asset': 'اثاثہ',
  'liability': 'واجب الادا رقم',
  'Account name': 'اکاؤنٹ کا نام',
  'Current balance': 'موجودہ بیلنس',
  'Asset': 'اثاثہ',
  'Liability': 'واجب الادا رقم',
  'Use online Markaz AI?': 'آن لائن مرکز AI استعمال کریں؟',
  'A limited summary of your financial information will be sent securely to Google Gemini to answer your question. Passwords, authentication tokens, contact details and complete transaction records are not included.':
      'آپ کے سوال کا جواب دینے کے لیے آپ کی مالی معلومات کا محدود خلاصہ محفوظ طریقے سے Google Gemini کو بھیجا جائے گا۔ پاس ورڈ، تصدیقی ٹوکن، رابطے کی تفصیلات اور مکمل لین دین شامل نہیں ہوں گے۔',
  'Continue locally': 'مقامی طور پر جاری رکھیں',
  'Use online AI': 'آن لائن AI استعمال کریں',
  'Online AI is unavailable. Showing a local answer instead.':
      'آن لائن AI دستیاب نہیں۔ اس کے بجائے مقامی جواب دکھایا جا رہا ہے۔',
  'Online AI is enabled. Only a limited financial summary is sent to Google Gemini. Identity, contact details, notes, receipts and individual transactions are not included.':
      'آن لائن AI فعال ہے۔ صرف محدود مالی خلاصہ Google Gemini کو بھیجا جاتا ہے۔ شناخت، رابطے کی تفصیلات، نوٹس، رسیدیں اور انفرادی لین دین شامل نہیں ہوتے۔',
  'Guests and users who do not provide online-AI consent use the local assistant. No financial data is sent to Google Gemini in local mode.':
      'مہمان اور آن لائن AI کی رضامندی نہ دینے والے صارفین مقامی اسسٹنٹ استعمال کرتے ہیں۔ مقامی موڈ میں کوئی مالی ڈیٹا Google Gemini کو نہیں بھیجا جاتا۔',
  'Disable online AI': 'آن لائن AI بند کریں',
  'Online AI consent was removed.': 'آن لائن AI کی رضامندی ختم کر دی گئی۔',
  'Online Markaz AI is optional. After you provide separate consent, a limited financial summary may be processed by Google Gemini to provide personalized financial assistance. Passwords, authentication tokens, contact details, notes, receipts and complete transaction records are excluded. Guest mode and local answers do not send financial information to Gemini.':
      'آن لائن مرکز AI اختیاری ہے۔ آپ کی الگ رضامندی کے بعد ذاتی مالی معاونت کے لیے ایک محدود مالی خلاصہ Google Gemini کے ذریعے پراسیس کیا جا سکتا ہے۔ پاس ورڈ، تصدیقی ٹوکن، رابطے کی تفصیلات، نوٹس، رسیدیں اور مکمل لین دین شامل نہیں ہوتے۔ مہمان موڈ اور مقامی جوابات Gemini کو مالی معلومات نہیں بھیجتے۔',
  'AI limitations': 'AI کی حدود',
  'Gemini responses are generated for informational purposes and may be incomplete or inaccurate. They are not financial, tax, legal or religious advice.':
      'Gemini کے جوابات معلوماتی مقصد کے لیے تیار کیے جاتے ہیں اور نامکمل یا غلط ہو سکتے ہیں۔ یہ مالی، ٹیکس، قانونی یا مذہبی مشورہ نہیں ہیں۔',
  'You can export or delete locally stored financial data from Settings. You can withdraw online-AI consent at any time from the Markaz AI privacy dialog without deleting local conversation history.':
      'آپ ترتیبات سے مقامی مالی ڈیٹا ایکسپورٹ یا حذف کر سکتے ہیں۔ آپ مقامی گفتگو کی ہسٹری حذف کیے بغیر مرکز AI کے رازداری ڈائیلاگ سے کسی بھی وقت آن لائن AI کی رضامندی واپس لے سکتے ہیں۔',
  'Encrypted data protection': 'خفیہ ڈیٹا کا تحفظ',
  'Secure setup could not be loaded.': 'محفوظ سیٹ اپ لوڈ نہیں ہو سکا۔',
  'Secure setup failed. Nothing was changed.':
      'محفوظ سیٹ اپ ناکام ہوگیا۔ کوئی تبدیلی نہیں کی گئی۔',
  'Save your recovery key': 'اپنی ریکوری کلید محفوظ کریں',
  'This key is shown once. Keep it somewhere private and separate from this phone. Mera Markaz cannot recover encrypted data without an authorized device or this key.':
      'یہ کلید صرف ایک بار دکھائی جاتی ہے۔ اسے نجی اور اس فون سے الگ جگہ محفوظ رکھیں۔ مجاز ڈیوائس یا اس کلید کے بغیر میرا مرکز خفیہ ڈیٹا بحال نہیں کر سکتا۔',
  'Enter the final 8 characters to confirm that you saved it.':
      'محفوظ کرنے کی تصدیق کے لیے آخری 8 حروف درج کریں۔',
  'Final 8 characters': 'آخری 8 حروف',
  'Cancel setup': 'سیٹ اپ منسوخ کریں',
  'Confirm recovery key': 'ریکوری کلید کی تصدیق کریں',
  'Encryption keys are protected on this device.':
      'خفیہ کاری کی کلیدیں اس ڈیوائس پر محفوظ ہیں۔',
  'Protect future encrypted records and backups with a device key and a recovery key.':
      'مستقبل کے خفیہ ریکارڈ اور بیک اپ کو ڈیوائس کلید اور ریکوری کلید سے محفوظ کریں۔',
  'Create or sign in to an account before enabling encrypted backup.':
      'خفیہ بیک اپ فعال کرنے سے پہلے اکاؤنٹ بنائیں یا سائن ان کریں۔',
  'Your recovery key is never uploaded or stored by Mera Markaz. Losing every authorized device and the recovery key makes encrypted data unrecoverable.':
      'آپ کی ریکوری کلید میرا مرکز کبھی اپ لوڈ یا محفوظ نہیں کرتا۔ تمام مجاز ڈیوائسز اور ریکوری کلید کھونے کی صورت میں خفیہ ڈیٹا بحال نہیں ہو سکتا۔',
  'Set up encrypted protection': 'خفیہ تحفظ قائم کریں',
  'Local encryption & optional recovery': 'مقامی خفیہ کاری اور اختیاری ریکوری',
  'Optional recovery is configured for this account.':
      'اس اکاؤنٹ کے لیے اختیاری ریکوری قائم ہے۔',
  'Local financial data is encrypted automatically on this device.':
      'مقامی مالی ڈیٹا اس ڈیوائس پر خودکار طور پر خفیہ ہے۔',
  'Guest data is encrypted locally. Sign in only if you want optional cloud backup and recovery later.':
      'مہمان ڈیٹا مقامی طور پر خفیہ ہے۔ صرف اس صورت میں سائن ان کریں جب آپ بعد میں اختیاری کلاؤڈ بیک اپ اور ریکوری چاہتے ہوں۔',
  'No action is required for local encryption. You may optionally create a recovery key for future encrypted cloud backup and another-device restore.':
      'مقامی خفیہ کاری کے لیے کسی کارروائی کی ضرورت نہیں۔ مستقبل کے خفیہ کلاؤڈ بیک اپ اور دوسری ڈیوائس پر بحالی کے لیے آپ اختیاری ریکوری کلید بنا سکتے ہیں۔',
  'Set up optional recovery': 'اختیاری ریکوری قائم کریں',
  'An encrypted Mera Markaz backup was saved locally:':
      'میرا مرکز کا خفیہ بیک اپ مقامی طور پر محفوظ کیا گیا:',
  'Create an authenticated encrypted .mmb backup.':
      'تصدیق شدہ خفیہ .mmb بیک اپ بنائیں۔',
  'Restore encrypted backup?': 'خفیہ بیک اپ بحال کریں؟',
  'Current records for this profile will be replaced only after the backup is authenticated and validated.':
      'اس پروفائل کے موجودہ ریکارڈ صرف بیک اپ کی تصدیق اور جانچ کے بعد تبدیل کیے جائیں گے۔',
  'Restore backup': 'بیک اپ بحال کریں',
  'Encrypted backup restored.': 'خفیہ بیک اپ بحال ہوگیا۔',
  'Backup could not be restored. No data was changed.':
      'بیک اپ بحال نہیں ہو سکا۔ کوئی ڈیٹا تبدیل نہیں کیا گیا۔',
  'Restore encrypted backup': 'خفیہ بیک اپ بحال کریں',
  'Authenticate and restore a local .mmb file.':
      'مقامی .mmb فائل کی تصدیق کرکے بحال کریں۔',
  'Authorized devices': 'مجاز ڈیوائسز',
  'Sign in to manage devices used for encrypted cloud recovery.':
      'خفیہ کلاؤڈ ریکوری کے لیے استعمال ہونے والی ڈیوائسز کا انتظام کرنے کے لیے سائن ان کریں۔',
  'Devices could not be loaded.': 'ڈیوائسز لوڈ نہیں ہو سکیں۔',
  'No cloud devices registered.': 'کوئی کلاؤڈ ڈیوائس رجسٹرڈ نہیں۔',
  'Revoke': 'منسوخ کریں',
  'pending': 'زیر التوا',
  'active': 'فعال',
  'revoked': 'منسوخ شدہ',
  'Restore encrypted data': 'خفیہ ڈیٹا بحال کریں',
  'Recovery key': 'ریکوری کلید',
  'Restore': 'بحال کریں',
  'Restore with recovery key': 'ریکوری کلید سے بحال کریں',
  'Recovery failed. Check the recovery key and try again.':
      'ریکوری ناکام ہوگئی۔ ریکوری کلید چیک کرکے دوبارہ کوشش کریں۔',
  'Enter your details': 'اپنی تفصیلات درج کریں',
  'Fields marked optional may be left empty.':
      'اختیاری خانے خالی چھوڑے جا سکتے ہیں۔',
  'What you need': 'آپ کو کیا درکار ہے',
  'How it is calculated': 'حساب کیسے کیا جاتا ہے',
  'Before you rely on it': 'نتیجے پر انحصار کرنے سے پہلے',
  'Estimate salary tax and monthly take-home before planning your budget.':
      'بجٹ بنانے سے پہلے تنخواہ ٹیکس اور ماہانہ ہاتھ میں آنے والی رقم کا تخمینہ لگائیں۔',
  'Your gross monthly salary and any other annual taxable income. Use amounts before tax deductions.':
      'اپنی مجموعی ماہانہ تنخواہ اور دیگر سالانہ قابل ٹیکس آمدنی درج کریں۔ ٹیکس کٹوتی سے پہلے کی رقم استعمال کریں۔',
  'Monthly salary is converted to annual income, other taxable income is added, and the configured progressive salary-tax slabs are applied.':
      'ماہانہ تنخواہ کو سالانہ آمدنی میں تبدیل کرکے دیگر قابل ٹیکس آمدنی شامل کی جاتی ہے اور مقررہ ٹیکس سلیب لاگو ہوتے ہیں۔',
  'Tax rules, exemptions, credits and filer status can change the final liability. Confirm the current tax year and FBR guidance.':
      'ٹیکس قواعد، چھوٹ، کریڈٹ اور فائلر حیثیت حتمی واجب الادا رقم بدل سکتے ہیں۔ موجودہ ٹیکس سال اور ایف بی آر رہنمائی کی تصدیق کریں۔',
  'Estimate electricity usage and charges before the official bill arrives.':
      'سرکاری بل آنے سے پہلے بجلی کے استعمال اور چارجز کا تخمینہ لگائیں۔',
  'Choose an input method': 'اندراج کا طریقہ منتخب کریں',
  'What the estimate includes': 'تخمینے میں کیا شامل ہے',
  'Why the official bill may differ': 'سرکاری بل مختلف کیوں ہو سکتا ہے',
  'Size a preliminary solar system from your electricity usage and available roof area.':
      'بجلی کے استعمال اور دستیاب چھت کے مطابق ابتدائی سولر سسٹم کا سائز معلوم کریں۔',
  'What you will learn': 'آپ کو کیا معلوم ہوگا',
  'Plan before purchasing': 'خریداری سے پہلے منصوبہ بنائیں',
  'Convert plot dimensions into the property units commonly used in Pakistan.':
      'پلاٹ کی پیمائش کو پاکستان میں عام جائیداد اکائیوں میں تبدیل کریں۔',
  'Measure the plot': 'پلاٹ کی پیمائش کریں',
  'Select the local Marla standard': 'مقامی مرلہ معیار منتخب کریں',
  'Optional price estimate': 'اختیاری قیمت کا تخمینہ',
  'Understand vehicle fuel average, trip cost and cost per kilometre.':
      'گاڑی کی فیول اوسط، سفر کی لاگت اور فی کلومیٹر خرچ سمجھیں۔',
  'Use the full-tank method': 'فل ٹینک طریقہ استعمال کریں',
  'Compare fairly': 'درست موازنہ کریں',
  'Review the basic conditions, understand Nisab, and calculate 2.5% of eligible net wealth.':
      'بنیادی شرائط دیکھیں، نصاب سمجھیں اور قابل زکوٰۃ خالص مال کا 2.5 فیصد حساب کریں۔',
  'When is Zakat applicable?': 'زکوٰۃ کب لاگو ہوتی ہے؟',
  'What is Nisab?': 'نصاب کیا ہے؟',
  'What wealth is usually included?': 'عام طور پر کون سا مال شامل ہوتا ہے؟',
  'What is generally excluded?': 'عام طور پر کیا شامل نہیں ہوتا؟',
  'Simple rule': 'سادہ اصول',
  'Confirm the basic conditions': 'بنیادی شرائط کی تصدیق کریں',
  'These checks help you review applicability; they are not a religious ruling.':
      'یہ چیکس اطلاق سمجھنے میں مدد دیتے ہیں؛ یہ شرعی فتویٰ نہیں ہیں۔',
  'I am Muslim': 'میں مسلمان ہوں',
  'Zakat is an obligation for eligible Muslims.':
      'اہل مسلمانوں پر زکوٰۃ فرض ہے۔',
  'My net eligible wealth reaches Nisab':
      'میرا خالص قابل زکوٰۃ مال نصاب تک پہنچتا ہے',
  'Use the current value of the Nisab standard you follow.':
      'جس نصاب معیار پر آپ عمل کرتے ہیں اس کی موجودہ قیمت استعمال کریں۔',
  'One lunar year has passed': 'ایک قمری سال گزر چکا ہے',
  'Confirm the Hawl rule that applies to your assets.':
      'اپنے اثاثوں پر لاگو حول کے حکم کی تصدیق کریں۔',
  'Your Zakatable assets': 'آپ کے قابل زکوٰۃ اثاثے',
  'Cash in hand and bank': 'نقد اور بینک بیلنس',
  'Gold value': 'سونے کی قیمت',
  'Silver value': 'چاندی کی قیمت',
  'Eligible investments and shares': 'قابل زکوٰۃ سرمایہ کاری اور حصص',
  'Business inventory and trade assets': 'کاروباری اسٹاک اور تجارتی اثاثے',
  'Recoverable money owed to you': 'قابل وصول رقم',
  'Other eligible assets': 'دیگر قابل زکوٰۃ اثاثے',
  'Please review and confirm all applicable conditions before calculating.':
      'حساب سے پہلے تمام قابل اطلاق شرائط دیکھ کر تصدیق کریں۔',
  'Enter consumed units directly, or leave that field empty and provide previous and current meter readings.':
      'استعمال شدہ یونٹس براہ راست درج کریں، یا یہ خانہ خالی چھوڑ کر پچھلی اور موجودہ میٹر ریڈنگ درج کریں۔',
  'The calculator applies configured residential energy slabs, fixed charges and your estimated tax or adjustment percentage.':
      'کیلکولیٹر مقررہ رہائشی یونٹ سلیب، فکسڈ چارجز اور آپ کے تخمینی ٹیکس یا ایڈجسٹمنٹ فیصد کو لاگو کرتا ہے۔',
  'Provider tariff, protected status, FCA, QTA, duties, arrears, subsidies and meter dates can change the final bill.':
      'فراہم کنندہ کے نرخ، پروٹیکٹڈ حیثیت، ایف سی اے، کیو ٹی اے، ڈیوٹیز، بقایا جات، سبسڈی اور میٹر تاریخیں حتمی بل بدل سکتی ہیں۔',
  'Use an average monthly kWh value from recent bills and estimate the shade-free roof area available for panels.':
      'حالیہ بلوں سے اوسط ماہانہ کلوواٹ آور لیں اور پینلز کے لیے سایہ سے پاک چھت کے رقبے کا اندازہ لگائیں۔',
  'See a suggested system size, approximate panel count, roof requirement, generation, savings and simple payback period.':
      'تجویز کردہ سسٹم سائز، اندازاً پینل تعداد، درکار چھت، پیداوار، بچت اور واپسی کی مدت دیکھیں۔',
  'Ask a qualified installer to inspect structure, shade, orientation, inverter limits, batteries and current net-metering rules.':
      'ماہر انسٹالر سے عمارت، سایہ، سمت، انورٹر حدود، بیٹریوں اور موجودہ نیٹ میٹرنگ قواعد کی جانچ کروائیں۔',
  'Enter length and width in feet. This simple calculator assumes a rectangular plot.':
      'لمبائی اور چوڑائی فٹ میں درج کریں۔ یہ سادہ کیلکولیٹر مستطیل پلاٹ فرض کرتا ہے۔',
  'Marla size is not identical everywhere. Confirm whether your locality uses 225, 250, 272.25 or another square-foot standard.':
      'مرلہ کا سائز ہر جگہ یکساں نہیں۔ تصدیق کریں کہ آپ کے علاقے میں 225، 250، 272.25 یا کوئی اور مربع فٹ معیار ہے۔',
  'Enter a price per Marla to estimate total price. Registration, taxes, development charges and agent fees are not included.':
      'کل قیمت کے تخمینے کے لیے فی مرلہ قیمت درج کریں۔ رجسٹریشن، ٹیکس، ترقیاتی چارجز اور ایجنٹ فیس شامل نہیں۔',
  'For a reliable average, reset the trip meter after filling, drive normally, refill fully, then enter distance and litres added.':
      'درست اوسط کے لیے ٹینک بھرنے کے بعد ٹرپ میٹر ری سیٹ کریں، معمول کے مطابق چلائیں، دوبارہ مکمل ٹینک بھریں اور فاصلہ و لیٹر درج کریں۔',
  'Fuel average is distance divided by litres. Trip cost is litres multiplied by price, and cost per kilometre is total cost divided by distance.':
      'فیول اوسط فاصلہ تقسیم لیٹر ہے۔ سفر کی لاگت لیٹر ضرب قیمت اور فی کلومیٹر خرچ کل لاگت تقسیم فاصلہ ہے۔',
  'Traffic, idling, tyre pressure, air conditioning, load and driving style affect consumption. Compare several full-tank entries.':
      'ٹریفک، گاڑی کا کھڑا چلنا، ٹائر پریشر، اے سی، وزن اور ڈرائیونگ انداز ایندھن پر اثر ڈالتے ہیں۔ کئی فل ٹینک اندراجات کا موازنہ کریں۔',
  'Zakat generally applies to a Muslim whose eligible net wealth reaches Nisab and remains at or above it for one lunar year. Detailed rulings may differ, so consult a trusted scholar when unsure.':
      'زکوٰۃ عام طور پر اس مسلمان پر لاگو ہوتی ہے جس کا خالص قابل زکوٰۃ مال نصاب تک پہنچے اور ایک قمری سال تک برقرار رہے۔ تفصیلی احکام مختلف ہو سکتے ہیں، اس لیے شک کی صورت میں معتبر عالم سے رجوع کریں۔',
  'Nisab is the minimum wealth threshold. It is commonly based on the current market value of 87.48 grams of gold or 612.36 grams of silver. Many scholars recommend the silver threshold because it benefits more people in need.':
      'نصاب مال کی کم از کم حد ہے۔ عام طور پر یہ 87.48 گرام سونے یا 612.36 گرام چاندی کی موجودہ قیمت پر مبنی ہوتا ہے۔ بہت سے علماء زیادہ ضرورت مندوں کے فائدے کے لیے چاندی کے نصاب کی سفارش کرتے ہیں۔',
  'Cash and bank balances, gold and silver, trade inventory, eligible investments, recoverable receivables and other assets held for growth or sale are commonly included.':
      'نقد و بینک بیلنس، سونا چاندی، تجارتی اسٹاک، قابل زکوٰۃ سرمایہ کاری، قابل وصول رقم اور بڑھوتری یا فروخت کے لیے رکھے اثاثے عام طور پر شامل ہوتے ہیں۔',
  'A primary residence, normal personal vehicle, clothing, household furniture and ordinary daily-use items are generally not included. Enter only immediately deductible liabilities after confirming the applicable ruling.':
      'بنیادی رہائش، عام ذاتی گاڑی، کپڑے، گھریلو فرنیچر اور روزمرہ استعمال کی اشیاء عموماً شامل نہیں ہوتیں۔ قابل اطلاق حکم کی تصدیق کے بعد صرف فوری قابل کٹوتی واجبات درج کریں۔',
  'If eligible assets minus deductible short-term liabilities meet the selected Nisab after one lunar year, estimated Zakat is 2.5% (1/40) of net eligible wealth.':
      'اگر قابل زکوٰۃ اثاثے منفی قابل کٹوتی قلیل مدتی واجبات ایک قمری سال بعد منتخب نصاب تک پہنچیں تو تخمینی زکوٰۃ خالص مال کا 2.5 فیصد یعنی چالیسواں حصہ ہے۔',
  'Assalam-o-Alaikum': 'السلام علیکم',
  'Press back again to exit the app':
      'ایپ بند کرنے کے لیے دوبارہ بیک بٹن دبائیں',
};
