import type { Metadata } from 'next';
import { DocumentShell } from '@/components/document-shell';

export const metadata: Metadata = { title: 'User guide', description: 'Learn how to install, set up and use Mera Markaz.' };
const sections = [{id:'install',label:'Install the app'},{id:'account',label:'Choose how to start'},{id:'home',label:'Set up your money'},{id:'tools',label:'Use calculators'},{id:'language',label:'Change language'},{id:'backup',label:'Sync & backup'}];
export default function Guide() { return <DocumentShell kicker="Step-by-step help" title="Your Mera Markaz user guide" intro="A simple walkthrough for installing the app, choosing an account mode, recording your finances and using its smart tools." sections={sections}>
  <section id="install"><h2>1. Install the app</h2><ol className="steps"><li>Open the official Mera Markaz listing on Google Play.</li><li>Tap <strong>Install</strong> and wait for Android to finish.</li><li>Open Mera Markaz from your app drawer. Keep the app updated to receive fixes and improvements.</li></ol><div className="notice">Only install Mera Markaz from its official Google Play listing or a testing link provided by Logivyre Labs.</div></section>
  <section id="account"><h2>2. Choose how to start</h2><h3>Continue as guest</h3><p>Guest mode lets you explore without creating an account. Your temporary session remains on the device when the app closes and ends only when you sign into an account or choose Log out.</p><h3>Create or use an account</h3><p>Sign in with email or Google. Creating an account from a guest profile can attach eligible activity from the current guest session. Signing into an existing account discards the guest session and restores that account’s available data.</p></section>
  <section id="home"><h2>3. Set up your money view</h2><ol className="steps"><li>Add an expense and choose the most relevant category.</li><li>Set a monthly or category budget and review your spending against it.</li><li>Create savings goals and Udhaar ledgers, then review your history for a quick monthly picture.</li></ol></section>
  <section id="tools"><h2>4. Use Pakistan-focused tools</h2><p>Open Tools to find electricity, fuel, salary tax and Zakat calculators. Enter the requested values, check the result and review any source or informational notice shown in the app. Calculations are estimates and are not professional financial, tax, legal or religious advice.</p></section>
  <section id="language"><h2>5. Change language</h2><p>Use the language control on the welcome screen or open Settings to switch between English and Urdu. Urdu uses a right-to-left layout where appropriate.</p></section>
  <section id="backup"><h2>6. Sync and backup</h2><p>Signed-in users can use supported encrypted sync and backup. Keep access to your sign-in method, use a secure device lock, and never share verification codes. Guest data is device-local unless it is attached during account creation.</p></section>
  </DocumentShell>; }
